CREATE TABLE IF NOT EXISTS `pick_up_point` (
    `id` bigint AUTO_INCREMENT PRIMARY KEY comment '主键id',
    `name` varchar(40) NOT NULL comment '自提点名称',
    `phone_number` varchar(14) NOT NULL comment '自提点电话',
    `province` varchar(20) NOT NULL comment '地址（省）',
    `province_id` int NOT NULL comment '省id',
    `city` varchar(20) NOT NULL comment '地址（市）',
    `city_id` int NOT NULL comment '市id',
    `district` varchar(20) NOT NULL comment '地址（区）',
    `district_id` int NOT NULL comment '区id',
    `detailed_address` varchar(100) NOT NULL comment '详细地址',
    `open_time` varchar(5) NOT NULL comment '营业开始时间',
    `close_time` varchar(5) NOT NULL comment '营业结束时间',
    `store_id` bigint NOT NULL comment '绑定门店id',
    `store_name` varchar(50) NOT NULL comment '绑定门店名称',
    `latitude` decimal(9, 6) NOT NULL comment '自提点坐标纬度',
    `longitude` decimal(9, 6) NOT NULL comment '自提点坐标经度',
    `status` tinyint(1) NOT NULL comment '状态标记 0停用 1启用',
    `transit_time` int NOT NULL DEFAULT '0' comment '在途时长',
    `service_day` varchar(20) NOT NULL DEFAULT '0' comment '履约日期，0~7多选，逗号间隔，默认0',
    `service_start_time` varchar(10) comment '履约开始时间',
    `service_end_time` varchar(10) comment '履约结束时间',
    `service_duration` int NOT NULL comment '履约时段间隔',
    `service_interval` int NOT NULL comment '履约波次间隔',
    `service_times` varchar(200) NOT NULL comment '波次 XX:XX-XX:XX，逗号间隔',
    `is_delete` tinyint(1) NOT NULL DEFAULT 0 comment '删除标记 0未删除 1已删除',
    `create_user` varchar(32) NOT NULL comment '创建用户',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP comment '创建时间',
    `update_user` varchar(32) NOT NULL comment '最后更新用户',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP comment '最后更新时间'
    ) ENGINE=InnoDB AUTO_INCREMENT=10000001 DEFAULT CHARSET=utf8 comment='自提点信息表';
